site_name: Marina mkdocks

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Practica 3.1: practica-3.1.md
    - Practica 4.5: practica-4.5.md

theme:
  name: material  
  palette:
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    primary: teal



extra:
  language: eu
