site_name: Marina mkdocks

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Practica 3.1: practica-3.1.md
    - Practica 4.5: practica-4.5.md

theme:
  name: material  

  palette:
    # Modo claro
    - scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Modo oscuro
    - scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  language: eu



extra:
  language: eu
