site_name: Marina mkdocks

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Practica 3.1: practica-3.1.md
    - Practica 4.5: practica-4.5.md

theme:
  name: dracula  


extra:
  language: eu
