site_name: Marina mkdocks

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Practica 1: practica1.md

theme:
  name: material  # ← Agrega el nombre del tema aquí
  palette:
    scheme: slate
    primary: teal

extra:
  language: eu