site_name: Marina mkdocks

nav:
    - Principal: index.md
    - Practica 3.1: practica-3.1.md
    - Practica 4.5: practica-4.5.md

theme:
  name: material  

  palette:
    # Modo claro
    - scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Modo oscuro
    - scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - header.autohide
    - navigation.footer


extra:
  language: eu
  social:
    - icon: fontawesome/brands/github 
        link: https://github.com/marinaferb92


plugins:
  - offline
